name: CVE RSS generator

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r python/requirements.txt
          
      - name: Push articles
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
        run: python3 python/CVE_RSS.py $GITHUBTOKEN
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update all the things!"
          commit_user_name: websecnews
          commit_user_email: websecnews@local
          commit_author: websecnews <websecnews@local>
